--- # This is a sample configuration file for the HealerDB service.
healerdb:
    connstr: "mongodb://localhost:27017"
    conncreds: 
        username:
        password:
    dbs: 
        - name: "enum"
          target_based: true
          doc_tree:
              - name: "db"
              - name: "target_name"
              - name: "target_handle"
              - name: "target_type"
              - name: "bb_platform"
              - name: "link_to_bb"
              - name: "domains"
                tree:
                  - name: "domain"
                  - name: "subdomains"
                    tree:
                        - name: "subdomain"
                        - name: "directories"
                          tree:
                              - name: "directory"
                              - name: "subdirectories"
                                tree:
                                    - name: "subdirectory"
                                    - name: "subdirectories"
                                    - name: "files"
                                    - name: "parameters"
                              - name: "files"
                              - name: "parameters"
              - name: "scopes_info"
                tree:
                    - name: "scopes"
                    - name: "scope_type"
                    - name: "scope_identifier"
                    - name: "scope_eligible_for_submissions"
                    - name: "scope_eligible_for_bounty"

        - name: "vuln"
          target_based: true
        - name: "watch"
          target_based: true
        - name: "notifio"
          target_based: false
        - name: "report"
          target_based: true
        - name: "schedule"
          target_based: true
        - name: "ca" 
          target_based: true
        - name: "web"
          target_based: false
        - name: "creds"
          target_based: false
        - name: "modules_api"
          target_based: false
        - name: "worker"
          target_based: false
        - name: "log"
          target_based: true